In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.array([5,6,7,8,9])

array([5, 6, 7, 8, 9])

In [18]:
#matrix
m = [1,2,3,4,5]

In [22]:
np.array(m)

array([1, 2, 3, 4, 5])

In [23]:
np.asanyarray([5,6,7,8,9])

array([5, 6, 7, 8, 9])

In [24]:
np.asanyarray(m)

array([1, 2, 3, 4, 5])

# deep and shallow copy

In [5]:
a = np.array([5,6,7,8,9])

In [6]:
# shallow copy
b = a
b

array([5, 6, 7, 8, 9])

In [7]:
b[0] = 898
b

array([898,   6,   7,   8,   9])

In [8]:
a

array([898,   6,   7,   8,   9])

In [9]:
# deep copy
c = np.copy(a)

In [10]:
c

array([898,   6,   7,   8,   9])

In [11]:
c[1] = 45
c

array([898,  45,   7,   8,   9])

In [12]:
a

array([898,   6,   7,   8,   9])

In [15]:
np.fromfunction(lambda x,y : x==y, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [16]:
np.fromfunction(lambda x,y : x+y, (3,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.]])

In [29]:
np.fromstring('6,7', dtype=int, sep=',')

array([6, 7])

In [30]:
a = [[3,4,5],[6,7,8,], [9,8,7]]

In [31]:
n = np.array(a)
n

array([[3, 4, 5],
       [6, 7, 8],
       [9, 8, 7]])

In [33]:
# dimension of array
n.ndim

2

In [34]:
# size of array  
n.size

9

In [35]:
# shape of array
n.shape

(3, 3)

In [36]:
m = np.array([5,6,7])
m.ndim

1

In [37]:
n.dtype

dtype('int32')

In [40]:
#np arange 
n = np.arange(2.5,9.87, 0.5)

In [41]:
list(n)

[2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5]

In [48]:
np.linspace(3,7,6)

array([3. , 3.8, 4.6, 5.4, 6.2, 7. ])

In [53]:
np.zeros((2,2,5,6))

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]])

In [55]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [59]:
# there is no np.twos but we can implement with broadcast
np.ones((2,3,4)) + 1
#np.ones((2,3,4)) * 2

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [ ]:
# random array - most the time close to zero or zero
np.empty((2,4))

In [64]:
# identity matrix - always sqare matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
np.logspace(5.6,7.8,6, base=2)

array([ 48.50293013,  65.79928491,  89.26359465, 121.09537878,
       164.27851489, 222.8609442 ])

In [70]:
# random array 
m = np.random.rand(4,5)

In [73]:
m.reshape(5,4)

array([[0.79903774, 0.91718214, 0.36931641, 0.35977368],
       [0.8452028 , 0.0478669 , 0.07248018, 0.98973453],
       [0.1695788 , 0.82623108, 0.24692633, 0.57069314],
       [0.65926735, 0.01209456, 0.9917743 , 0.20713017],
       [0.95630596, 0.19923755, 0.99602698, 0.79021399]])

In [74]:
m.reshape(10,-2233)

array([[0.79903774, 0.91718214],
       [0.36931641, 0.35977368],
       [0.8452028 , 0.0478669 ],
       [0.07248018, 0.98973453],
       [0.1695788 , 0.82623108],
       [0.24692633, 0.57069314],
       [0.65926735, 0.01209456],
       [0.9917743 , 0.20713017],
       [0.95630596, 0.19923755],
       [0.99602698, 0.79021399]])