In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.array([5,6,7,8,9])

array([5, 6, 7, 8, 9])

In [18]:
#matrix
m = [1,2,3,4,5]

In [22]:
np.array(m)

array([1, 2, 3, 4, 5])

In [23]:
np.asanyarray([5,6,7,8,9])

array([5, 6, 7, 8, 9])

In [24]:
np.asanyarray(m)

array([1, 2, 3, 4, 5])

# deep and shallow copy

In [5]:
a = np.array([5,6,7,8,9])

In [6]:
# shallow copy
b = a
b

array([5, 6, 7, 8, 9])

In [7]:
b[0] = 898
b

array([898,   6,   7,   8,   9])

In [8]:
a

array([898,   6,   7,   8,   9])

In [9]:
# deep copy
c = np.copy(a)

In [10]:
c

array([898,   6,   7,   8,   9])

In [11]:
c[1] = 45
c

array([898,  45,   7,   8,   9])

In [12]:
a

array([898,   6,   7,   8,   9])

In [15]:
np.fromfunction(lambda x,y : x==y, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [16]:
np.fromfunction(lambda x,y : x+y, (3,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.]])

In [29]:
np.fromstring('6,7', dtype=int, sep=',')

array([6, 7])

In [30]:
a = [[3,4,5],[6,7,8,], [9,8,7]]

In [31]:
n = np.array(a)
n

array([[3, 4, 5],
       [6, 7, 8],
       [9, 8, 7]])

In [33]:
# dimension of array
n.ndim

2

In [34]:
# size of array  
n.size

9

In [35]:
# shape of array
n.shape

(3, 3)

In [36]:
m = np.array([5,6,7])
m.ndim

1

In [37]:
n.dtype

dtype('int32')

In [40]:
#np arange 
n = np.arange(2.5,9.87, 0.5)

In [41]:
list(n)

[2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5]

In [48]:
np.linspace(3,7,6)

array([3. , 3.8, 4.6, 5.4, 6.2, 7. ])

In [53]:
np.zeros((2,2,5,6))

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]])

In [55]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [59]:
# there is no np.twos but we can implement with broadcast
np.ones((2,3,4)) + 1
#np.ones((2,3,4)) * 2

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [ ]:
# random array - most the time close to zero or zero
np.empty((2,4))

In [64]:
# identity matrix - always sqare matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
np.logspace(5.6,7.8,6, base=2)

array([ 48.50293013,  65.79928491,  89.26359465, 121.09537878,
       164.27851489, 222.8609442 ])

In [70]:
# random array 
m = np.random.rand(4,5)

In [73]:
m.reshape(5,4)

array([[0.79903774, 0.91718214, 0.36931641, 0.35977368],
       [0.8452028 , 0.0478669 , 0.07248018, 0.98973453],
       [0.1695788 , 0.82623108, 0.24692633, 0.57069314],
       [0.65926735, 0.01209456, 0.9917743 , 0.20713017],
       [0.95630596, 0.19923755, 0.99602698, 0.79021399]])

In [74]:
m.reshape(10,-2233)

array([[0.79903774, 0.91718214],
       [0.36931641, 0.35977368],
       [0.8452028 , 0.0478669 ],
       [0.07248018, 0.98973453],
       [0.1695788 , 0.82623108],
       [0.24692633, 0.57069314],
       [0.65926735, 0.01209456],
       [0.9917743 , 0.20713017],
       [0.95630596, 0.19923755],
       [0.99602698, 0.79021399]])

In [78]:
a =np.random.randint(3,8,(5,7))

In [79]:
a[0:2,0:2]

array([[3, 6],
       [4, 3]])

In [80]:
a > 5

array([[False,  True, False, False, False, False,  True],
       [False, False,  True,  True, False, False,  True],
       [ True, False,  True,  True, False, False,  True],
       [ True,  True, False, False,  True, False,  True],
       [False, False,  True, False,  True,  True,  True]])

In [84]:
m = np.array([[3,4,5],[5,6,7]])

In [85]:
n = np.array([[6,2,1],[2,3,4]])

In [86]:
m+n

array([[ 9,  6,  6],
       [ 7,  9, 11]])

In [87]:
m-n

array([[-3,  2,  4],
       [ 3,  3,  3]])

In [88]:
# this is not matrix multiplication but index wise operation
m*n

array([[18,  8,  5],
       [10, 18, 28]])

In [90]:
m1 = np.array([[0,1],[2,3]])

In [91]:
m2 = np.array([[2,3],[1,8]])

In [92]:
# matrix mutliplication - use @ 
m1@m2

array([[ 1,  8],
       [ 7, 30]])

In [93]:
m1

array([[0, 1],
       [2, 3]])

In [95]:
# power of operation - **
m1**2

array([[0, 1],
       [4, 9]], dtype=int32)

In [96]:
pow(m1,2)

array([[0, 1],
       [4, 9]], dtype=int32)

In [99]:
m = np.zeros((3,4))
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
n1= np.array([1,3,4,2])

In [102]:
m+n1

array([[1., 3., 4., 2.],
       [1., 3., 4., 2.],
       [1., 3., 4., 2.]])

In [103]:
m +2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [109]:
m3= np.random.rand(4,5).reshape(10,2)

In [110]:
m4 = np.random.rand(4,5).reshape(10,2)
m4

array([[0.72175169, 0.08989802],
       [0.76849062, 0.45482377],
       [0.38975016, 0.98450172],
       [0.51288714, 0.59256606],
       [0.71917699, 0.6651558 ],
       [0.41710046, 0.45445335],
       [0.08689618, 0.57640604],
       [0.50731146, 0.33986281],
       [0.14745961, 0.25343729],
       [0.14432997, 0.09916429]])

In [111]:
np.sqrt(m4)

array([[0.8495597 , 0.29982998],
       [0.87663597, 0.67440624],
       [0.62429973, 0.9922206 ],
       [0.7161614 , 0.76978313],
       [0.84804303, 0.81557084],
       [0.64583315, 0.67413155],
       [0.29478158, 0.75921409],
       [0.712258  , 0.58297754],
       [0.3840047 , 0.50342555],
       [0.37990785, 0.31490362]])

In [112]:
np.exp(m3)

array([[2.60058999, 1.09866609],
       [2.43008223, 1.571689  ],
       [2.70391642, 2.35827285],
       [1.40834807, 1.75554848],
       [1.09274106, 1.10667058],
       [2.29384909, 1.64366055],
       [1.03497074, 2.45498841],
       [2.50781896, 2.48170897],
       [1.90687713, 1.99643628],
       [2.61276583, 1.68557574]])

In [113]:
np.log10(m3)

array([[-0.01966099, -1.02642514],
       [-0.05162367, -0.34471666],
       [-0.00230734, -0.06654839],
       [-0.46544413, -0.24966032],
       [-1.0521289 , -0.99415039],
       [-0.08080093, -0.30370846],
       [-1.46378064, -0.04666465],
       [-0.03648915, -0.04146124],
       [-0.19012603, -0.16029341],
       [-0.01754361, -0.28224032]])

In [114]:
m3

array([[0.95573834, 0.0940968 ],
       [0.8879251 , 0.45215084],
       [0.99470125, 0.85792951],
       [0.34241743, 0.56278133],
       [0.08868927, 0.10135603],
       [0.83023123, 0.4969258 ],
       [0.03437315, 0.89812204],
       [0.91941343, 0.90894742],
       [0.64546689, 0.69136373],
       [0.96040936, 0.52210719]])

In [115]:
m4

array([[0.72175169, 0.08989802],
       [0.76849062, 0.45482377],
       [0.38975016, 0.98450172],
       [0.51288714, 0.59256606],
       [0.71917699, 0.6651558 ],
       [0.41710046, 0.45445335],
       [0.08689618, 0.57640604],
       [0.50731146, 0.33986281],
       [0.14745961, 0.25343729],
       [0.14432997, 0.09916429]])

In [116]:
np.fmod(m3,m4)

array([[0.23398665, 0.00419879],
       [0.11943448, 0.45215084],
       [0.21520093, 0.85792951],
       [0.34241743, 0.56278133],
       [0.08868927, 0.10135603],
       [0.41313077, 0.04247245],
       [0.03437315, 0.321716  ],
       [0.41210198, 0.22922181],
       [0.05562846, 0.18448915],
       [0.09442954, 0.02628575]])